rails/bd/config/routes.rb
Rails.application.routes.draw do

  resources :testable_class do
    collection do
      get :new_calculation
      post :calculate
    end
  end

end

rails/bd/app/models/testable_class1.rb
class TestableClass1
  def calculate(n)
    return n
  end
end

rails/bd/app/models/testable_class2.rb
class TestableClass2
  attr_accessor :divisor_1
  attr_accessor :divisor_2

  def initialize(div1=3, div2=5)
    divisor_1 = div1
    divisor_2 = div2
  end

  def calculate(n)
    (0..(n-1)).to_a.select{ |i| i.modulo(divisor_1 || 3) == 0 || i.modulo(divisor_2 || 5) == 0 }.inject(:+)
  end
end

rails/bd/app/models/testable_class3.rb
class TestableClass3
  def calculate(n)
    a = (1..n).to_a.inject(0) { |i,j| i+j*j }
    b = (1..n).to_a.inject(0) { |i,j| i+j }
    b*b-a
  end
end

rails/bd/app/models/testable_class4.rb
# calculate fibonacci number
class TestableClass4
  def calculate(n)
    return n if (0..1).include? n
    calculate(n-1) + calculate(n-2) if n > 1
  end
end

rails/bd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/bd/app/controllers/testable_class_controller.rb
class TestableClassController < ApplicationController
  def new_calculation
  end

  def calculate
    @calculation_value = params["testable"]["calculation_value"].to_i
    @problem = Object.const_get(params["testable"]["testable_class"]).new
    @result = @problem.calculate(@calculation_value)
  end
end

rails/bd/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/bd/app/helpers/testable_class1_helper.rb
module TestableClass1Helper
end

rails/bd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/bd/app/views/testable_class/calculate.html.erb
<h2>Result</h2>

<%= ["You tested", @problem.class.name, "with the n as", @calculation_value].join(" ") %>.
<%= ["The result is:", @result].join(" ") %>.

<%= link_to 'Test again!', new_calculation_testable_class_index_path %>

rails/bd/app/views/testable_class/new_calculation.html.erb
<h2>Calculate value in a testable class</h2>
<%= form_for "testable", url: :calculate_testable_class_index, method: :post do |f| %>
  <p>
    <%= f.label :testable_class %>
    <%= f.select :testable_class, [TestableClass1, TestableClass2, TestableClass3, TestableClass4] %>
    <%= f.label :calculation_value %>
    <%= f.text_field :calculation_value %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>